# Generated by Django 4.2 on 2023-04-23 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_job_met_req_alter_edu_level_alter_job_exp_req_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 23, 19, 6, 59, 932599)),
        ),
    ]
