# Generated by Django 4.2 on 2023-04-27 10:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_job_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edu',
            name='level',
            field=models.CharField(choices=[('basic', 'basic'), ('higher', 'higher'), ('graduation', 'graduation'), ('post graduation', 'post graduation'), ('doctorate', 'doctorate'), ('certifications', 'certifications')], default='basic', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 27, 15, 30, 35, 608565)),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app', to='base.application')),
            ],
        ),
    ]
