# Generated by Django 4.2 on 2023-04-23 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_applicant_user_alter_job_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 23, 17, 5, 35, 301946)),
        ),
    ]
