# Generated by Django 4.1.7 on 2023-04-11 09:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_skill_remove_user_bio_remove_user_is_writer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='edu_req',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='exp_req',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_req',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 11, 14, 31, 17, 748718)),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='User',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiters', to=settings.AUTH_USER_MODEL),
        ),
    ]
