# Generated by Django 4.1.7 on 2023-04-11 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_job_edu_req_job_exp_req_job_is_active_job_skills_req_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 11, 14, 37, 39, 565791)),
        ),
    ]
