# Generated by Django 4.1.7 on 2023-04-22 10:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_job_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='edu',
            name='level',
            field=models.CharField(choices=[('basic', 'basic'), ('higher', 'higher'), ('graduation', 'graduation'), ('post graduation', 'post graduation'), ('doctorate', 'doctorate'), ('certifications', 'certifications')], default='basic', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='grade_req',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='meet_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(null=True, upload_to='resume/'),
        ),
        migrations.AlterField(
            model_name='edu',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='edu_req',
            field=models.CharField(choices=[('basic', 'basic'), ('higher', 'higher'), ('graduation', 'graduation'), ('post graduation', 'post graduation'), ('doctorate', 'doctorate'), ('certifications', 'certifications')], default='graduation', max_length=50),
        ),
        migrations.RemoveField(
            model_name='job',
            name='skills_req',
        ),
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 22, 15, 30, 38, 211489)),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_applied', 'not_applied'), ('applied', 'applied'), ('shortlisted', 'shortlisted'), ('interviewed', 'interviewed'), ('rejected', 'rejected'), ('accepted', 'accepted')], default='not_applied', max_length=50)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app', to='base.applicant')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app', to='base.job')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='skills_req',
            field=models.ManyToManyField(blank=True, null=True, to='base.skill'),
        ),
    ]
